# Generated by Django 3.2 on 2021-11-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Адрес'),
        ),
    ]
