# Generated by Django 3.2 on 2021-11-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20211107_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Обработанный'), ('UNPROCESSED', 'Необработанный')], default='UNPROCESSED', max_length=16, verbose_name='Статус заказа'),
        ),
    ]
