# Generated by Django 3.2 on 2021-11-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20211107_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('СARD', 'Электронно')], default='CASH', max_length=8, verbose_name='Способ оплаты'),
        ),
    ]
