# Generated by Django 3.2 on 2021-11-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('СARD', 'Электронно')], db_index=True, default='CASH', max_length=8, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Обработанный'), ('UNPROCESSED', 'Необработанный')], db_index=True, default='UNPROCESSED', max_length=16, verbose_name='Статус заказа'),
        ),
    ]
