# Generated by Django 3.2 on 2021-11-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20211109_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('СARD', 'Электронно')], db_index=True, max_length=8, verbose_name='Способ оплаты'),
        ),
    ]
